### ISSUE TITLE
Docker command returns error, make sure you run this program as admin/root user.

### ISSUE THREAD

**Issue by DuckersMcQuack** [smy20011/dreambooth-gui#10]
Docker command returns error, make sure you run this program as admin/root user.

'docker version' output: error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.

Installed all requirements, still doesn't work.

**Comment by niffelheim87** [comment]
> Docker command returns error, make sure you run this program as admin/root user.
> 
> 'docker version' output: error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
> 
> Installed all requirements, still doesn't work.

I had that error, make sure Docker Desktop is running. The exe does not start Docker Desktop on its own.
