### ISSUE TITLE
GENERAL QUESTION (or feature request) -- What did I just train?

### ISSUE THREAD

**Issue by Duemellon** [smy20011/dreambooth-gui#15]
Is there a way to save a file alongside the MODEL/CKPT that records what you trained for that one? Possibly a document that allows for accumulative values once the "use local CKPT for base" feature is implemented? 

Yes, I know, I can keep it as a text file myself.

But just thinking/wondering if there's a way to put a marker that follows the CKPT itself so something could read it later & say something like

**_base CKPT 1_4
Token:: Buddha Class: Person added [date/time]
Token: Sloppy Class: Style added [date/time]_**

Is there a current way for me to identify this that I just don't know of?

**Comment by smy20011** [comment]
It's in the roadmap :)

**Comment by smy20011** [comment]
It's implemented in the 0.1.6 version. It will save the training config in the folder as a JSON.
