### ISSUE TITLE
ISSUE failed to create directory?

### ISSUE THREAD

**Issue by Duemellon** [smy20011/dreambooth-gui#2]
When telling it to start I got:
Failed to create directory C:\... (username\appdata\roaming\smy20011.dreambooth\face

tried class "face:"
installed this on E: not C:

Does this need to be a C: install?

**Comment by smy20011** [comment]
No need for that, but I think you may want to close the program and restart.

**Comment by Duemellon** [comment]
restarted Same error. 
Did a file search for "sym20011.dreambooth" on my C:
**_C:\Users\%username%AppData\Local\smy20011.dreambooth_**

it appears to be looking for it in roaming, not local & messing it up

**Comment by alexanderdutton** [comment]
I had the same issue and ultimately just created the directory on its behalf, which let it proceed, but ran into another issue subsequently.

**Comment by mindrages** [comment]
Same Issue.
Copying the whole folder structure from local to roaming seems to have worked for me.
Training started and is running for 30 Minutes now without (noticeable) issues.

**Comment by Duemellon** [comment]
IDK how to tell when it's sdone. How to tell? where do I get the CKPT?

**Comment by Duemellon** [comment]
I've run it 3x to the point where the [stop] button switched back to [start] but no file was created on my local drive per the Output Dir 

I guess that's the nofication. The 4th time I ran it to a dir different than the Pick Image dir. Now it's a bunch of folders. I'm looking at the original item to see how to convert it to a CKPT for use with AUTOMATIC1111

**Comment by mindrages** [comment]
This python script (by Jachiam) can be used to convert the output files into a single .ckpt:
[https://gist.github.com/jachiam/8a5c0b607e38fcc585168b90c686eb05](url)

You can run it from a normal windows command prompt, assuming python is installed correctly (path and stuff).
All it wants is the input and output directory as parameters.
(Here, too, the output directory needs to be different from the input one.)

**Comment by Duemellon** [comment]
Thanks for that tip Mindrages. Unfortunately the link you provided doesn't work. I went to Jachiam's Github & found **_convert_diffusers_to_sd_colab.py_** which I think is what you were referencing.

Being a newb to all this IDK how to use a py. Do I simply create a text, drop the code in, rename extension to .py & then go into Anaconda & launch? Wouldn't I need to add parameters or something? 

Am I close to correct?

**Comment by smy20011** [comment]
Should be solved in cd2697f2

**Comment by Duemellon** [comment]
So I created a BAT file, added the lines, edited the last ones to match the paths based on the folder the bat was in
**_MODEL_PATH = "/folder"
CHECKPOINT_PATH = "/ckpt/checkpoint.ckpt"_**

where the bat is in %folder/
and the DB root folder is %folder/folder
and I created a folder ckpt at %folder/ckpt
========== fail

Tried running the BAT without those items modified
========== fail

Put all those lines into a .PY
launched anaconda
typed **_convert_diffusers_to_sd_colab.py_** 
launches MS Vis Studio
========== fail

The Git for this doesn't show how to run it. Doesn't show where the parameters are in a way I understand. Is the first parameter the origin folder or the destination? Is it double -- or a single - 
: L Unfortunately 

Thanks for your attempts to help
