### ISSUE TITLE
Config Trainer Model settings question

### ISSUE THREAD

**Issue by codestuff001** [smy20011/dreambooth-gui#27]
I'm a little confused about selecting the model in the Config Trainer settings. If I'm just selecting the folder that the model is in, will it use whatever .ckpt file is in the folder, or does the .ckpt file need a specific filename?

**Comment by smy20011** [comment]
You need to convert the ckpt to diffusers :( Will try to add auto conversion later.

**Comment by codestuff001** [comment]
This was helpful, thanks!
