### ISSUE TITLE
Dreambooth-gui stuck waiting

### ISSUE THREAD

**Issue by codestuff001** [smy20011/dreambooth-gui#28]
The process seems to be stuck waiting. There's no GPU activity or error message. It does create a class image folder under C:\Users\username\AppData\Roaming\smy20011.dreambooth", but there are no images in it.

Running on Windows 10 (Build 19044) with Docker and WSL2 installed.

![221031-191516-dreambooth-gui](https://user-images.githubusercontent.com/111013672/199127932-6c5cd0e0-28bd-4537-bd43-e944601adb38.jpg)
![221031-191728-dreambooth-gui](https://user-images.githubusercontent.com/111013672/199127947-0f99ab0b-9a35-4974-96cc-6d380803d83d.jpg)

**Comment by codestuff001** [comment]
I walked away for 45 min, and when I came back I got this error: 
![221031-203917-dreambooth-gui](https://user-images.githubusercontent.com/111013672/199134399-71b95771-ea75-4a0c-9b94-f520962d7cba.jpg)

**Comment by smy20011** [comment]
Do you have output in the output textarea? It seems you train failed.

**Comment by codestuff001** [comment]
I got it to work finally. I don't know if it was the cause of this specific issue, but I finally got it to work using a diffuser (.bin) version of the CKPT file for the local model.
