### ISSUE TITLE
Config Trainer Settings Confusion

### ISSUE THREAD

**Issue by codestuff001** [smy20011/dreambooth-gui#33]
There are 2 fields in the "Config Trainer" tab labeled "Training Steps"- I'm guessing it's a typo. What are they for?
![Dreambooth-GUI Screenshot](https://i.imgur.com/o17kZzb.jpg)

Are they for `--max_train_steps` and `--learning_rate` from Shavim's Dreambooth notebook?
![Shavim's Dreambooth Notebook Screenshot](https://i.imgur.com/xrfduFt.jpg)

**Comment by smy20011** [comment]
Fixed in v0.1.8
