### ISSUE TITLE
Prior-Preservation Loss (Class Training)

### ISSUE THREAD

**Issue by codestuff001** [smy20011/dreambooth-gui#34]
In Shavim's DreamBooth notebook, there are prior-preservation loss options available:

 ```
export CLASS_DIR="path-to-class-images"

  --class_data_dir=$CLASS_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --class_prompt="a photo of dog" \
  --num_class_images=200 \
```

Does Dreambooth-GUI support prior-preservation loss?

**Comment by smy20011** [comment]
It's set to 1.0 automatically.

**Comment by codestuff001** [comment]
Do you know where the class images are stored?

**Comment by smy20011** [comment]
Default is 100 and it's stored in the %APP_DIR%/smy20011.dreambooth

**Comment by codestuff001** [comment]
Got it, Thanks!
