### ISSUE TITLE
Process stops with read-only issue

### ISSUE THREAD

**Issue by 10001001011010111010** [smy20011/dreambooth-gui#46]
Any help would be very much appreciated -
Thanks!

...
...
63041bc7286a: Retrying in 4 seconds
e84ba40a3ba2: Retrying in 2 seconds
389cef77d3f2: Retrying in 2 seconds
63041bc7286a: Retrying in 3 seconds
e84ba40a3ba2: Retrying in 1 second
389cef77d3f2: Retrying in 1 second
63041bc7286a: Retrying in 2 seconds
63041bc7286a: Retrying in 1 second
docker: open /var/lib/docker/tmp/GetImageBlob3761715167: read-only file system.
See 'docker run --help'.

**Comment by smy20011** [comment]
I think you need to make sure you have enough space in C in order to install the docker image.

**Comment by 10001001011010111010** [comment]
Thanks, now I have 60Gb free...  but then this occured:

454b4e6dabd9: Verifying Checksum
454b4e6dabd9: Download complete
08c0b6423a55: Download complete
63041bc7286a: Download complete
e84ba40a3ba2: Verifying Checksum
e84ba40a3ba2: Download complete
docker: failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/5dcc93d5bfcacc7c69c93574e0bb690988519329358679a2d45b82a052a915f8/merged: too many levels of symbolic links.
See 'docker run --help'.

**Comment by smy20011** [comment]
Maybe you can try to remove docker image in the docker UI and rerun it.

**Comment by dehewgs** [comment]
> Maybe you can try to remove docker image in the docker UI and rerun it.

Do you think you could give a more detailed walkthrough of this process? I'm having the exact same issue.

**Comment by 10001001011010111010** [comment]
Docker shows no images to delete in UI.

Will try THIS next since it seems to match my case (running out of space before...)
https://github.com/docker/for-win/issues/5763#issuecomment-936254676

**Comment by smy20011** [comment]
> > Maybe you can try to remove docker image in the docker UI and rerun it.
> 
> Do you think you could give a more detailed walkthrough of this process? I'm having the exact same issue.

https://github.com/docker/for-win/issues/5763#issuecomment-936254676

Like this, I think it's because you previous docker pull result in an incomplete state thus trigger this error.
