### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by dehewgs** [smy20011/dreambooth-gui#47]
When I try to train I get this error: 

Unable to find image 'smy20011/dreambooth:latest' locally
docker: Error response from daemon: error creating temporary lease: write /var/lib/desktop-containerd/daemon/io.containerd.metadata.v1.bolt/meta.db: read-only file system: unknown.

**Comment by smy20011** [comment]
I think make sure you have enough space in C in order to download docker image.
