### ISSUE TITLE
Doesn't make full use of the graphics card

### ISSUE THREAD

**Issue by cerega66** [smy20011/dreambooth-gui#50]
When I start training using a сlass promts, when loading images of a class, the dreambooth stops using the video card core to the full (the frequency drops to 780 MHz, my standard frequency when loading is 1920 MHz) which gives me a slow learning speed of 1.2 s/it. However, if you run something in the background, for example, furmark, then the learning rate rises to 1.3 it/s, as does the core frequency (1920 MHz). Sometimes it is possible to start without dropping the frequency. Also, the drop in frequency is not observed when learning without a сlass promts.

My system:
Windows 10 22h2
amd 5600x
48 GB RAM
rtx 3060 12GB

Gui 0.1.8(in 0.1.6 too)

Arguments:
--mixed_precision=fp16
--train_batch_size=1
--gradient_accumulation_steps=1
--gradient_checkpointing
--use_8bit_adam

Any ideas why this is happening?

**Comment by smy20011** [comment]
When loading the class images, the process is limited by the speed of memory => GPU instead of GPU processing speed. We don't implement fast image loading because the benefit is small (10-30 sec for a 10 min training) and does not work if you don't have a good CPU & fast memory.
