### ISSUE TITLE
FEATURE REQUEST: Dreambooth to CKPT conversion built-in

### ISSUE THREAD

**Issue by Duemellon** [smy20011/dreambooth-gui#6]
Can you add in a button or switch that will allow the output to automatically generate as a CKPT? 
is a AEV file that is generate the same as the Hypernetwork file that can be used? or is that something else?

Thanks very much for this GUI. I've been desperate for someone to make a DB gui.

**Comment by bbecausereasonss** [comment]
This (there are scripts that do that already floating around) 

and

We should be able to use a local ckpt model instead of a hugging face tokenized one.

**Comment by Duemellon** [comment]
I tried using those others & they failed : L 
Someone gave me a PY to run but I wasn't sure how to launch it. I put the lines in a BAT that I ran from Anaconda but nothing came of it

If you can lead me to one & assist that would be great!

I can see the upcoming efforts on this & local CKPT is in the works as well as a conversion to CKPT. Which is great. But it seems like only one person & I would like to test the validity of the DB files I generated by converting to CKPT now.  Any ideas?

**Comment by bbecausereasonss** [comment]
That py file needs to be run through something like a Jupyter notebook.

**Comment by Duemellon** [comment]
Unfortunately not sure how to do that

**Comment by jtkelm2** [comment]
So you're saying that the command `python .\convert_diffusers_to_sd.py --model_path .\Model --checkpoint_path .\output.ckpt` didn't work for you? What went wrong?

**Comment by jtkelm2** [comment]
Sorry if my command wasn't clear, the _only_ thing you should be replacing should be .\Model (and output.ckpt, if you want to care to change the saved filename). In my case, my command looks like `python .\convert_diffusers_to_sd.py --model_path .\PutHere --checkpoint_path .\output.ckpt` where PutHere is a folder in the same directory as the script:

![image](https://user-images.githubusercontent.com/28983469/197292809-a11e3e04-1684-44a7-b1c8-5fa56c703325.png)

**Comment by smy20011** [comment]
Supported in 8da91348dcee361a1a8649cbb4ebbd7a8471f7b7 and relase 1.5

**Comment by smy20011** [comment]
Thank you @jtkelm2 for answering questions.

**Comment by bbecausereasonss** [comment]
Thanks! release 1.5 is not on the releases page, so has not been released yet?

**Comment by smy20011** [comment]
> bbecausereasonss

https://github.com/smy20011/dreambooth-gui/releases/tag/v0.1.5

.msi should be ready within 5 mins. It just take time for CI to run.

**Comment by bbecausereasonss** [comment]
Thanks so much!
