### ISSUE TITLE
Why is huggingface needed to run this? Didn't see it mentioned anywhere in the repo

### ISSUE THREAD

**Issue by Giganoob23** [smy20011/dreambooth-gui#65]
I wanna run the training locally as stable diffusion does not support NSFW models. Why is a huggingface token needed? Is that safe?

Edit: Also why on earth is this using 32GB of ram? Nearly crashed my entire system running on default settings. Even after stopping the program and shutting down docker from task manager i still see 3.5gb of ram being used by the virtual environment i had to install for this to work. Fastest uninstall of my life.

**Comment by futurevessel** [comment]
The huggingface token is needed to download the default model (1.4) and I believe some other needed files when you first use the image, technically it should not be needed beyond that and while you still need to have it set in the field, I don't think it's any longer accessed for anything.

In 1.9 alpha, you can train against any model you want, just click in the 'Model' field and locate a .ckpt you want to train against.

I've never had this use anywhere near 32gb of ram, what was the program doing at the time ?

**Comment by smy20011** [comment]
Model conversion need more memory due to you have to load two version of model in the memory and that takes more memory that needed.

Token is needed for people use diffusers model instead of local model. You can type 1234 if you don't need that token.
